'use strict';
(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],tool=$('main').dataset.tool;
$('.burger').onclick=()=>$('.nl').classList.toggle('open'); $$('.nb').forEach(b=>b.onclick=()=>$('.nl').classList.remove('open')); $('.tog').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='light'?'dark':'light'};
const val=id=>$('#'+id).value.trim(),num=id=>Number(val(id)),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n);
const status=s=>$('#status').textContent=s;
const result=h=>$('#result').innerHTML=h;
const metrics=entries=>'<div class="metrics">'+entries.map(([l,v])=>`<div class="metric"><strong>${v}</strong><small>${l}</small></div>`).join('')+'</div>';
function save(blob,name){const a=document.createElement('a');const u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),15000)}
function valid(n,min,max,label){if(!Number.isFinite(n)||n<min||n>max)throw Error(`${label} must be between ${min} and ${max}.`);return n}
function bind(id,fn){$('#'+id)?.addEventListener('click',async()=>{status('');try{await fn()}catch(e){status(e.message||'Could not finish. Please check your entries.')}})}
let libPromise;
async function pdfLib(){if(!libPromise)libPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='pdf-lib.min.js';s.onload=resolve;s.onerror=()=>{libPromise=null;reject(Error('PDF library could not load. Check your connection.'))};document.head.append(s)});await libPromise;return window.PDFLib}
async function imageFile(file){if(!file||!/^image\/(jpeg|png|webp)$/.test(file.type))throw Error('Choose a JPEG, PNG or WebP image.');if(file.size>30*1024*1024)throw Error('Please use an image under 30 MB.');const url=URL.createObjectURL(file);try{return await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('This image could not be opened. Try JPEG or PNG.'));im.src=url})}finally{URL.revokeObjectURL(url)}}
const canvas=(w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;return c};
const blob=(c,q=.92)=>new Promise((r,j)=>c.toBlob(b=>b?r(b):j(Error('Could not create image.')),'image/jpeg',q));
function drawFit(im,c,cover=false){const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);const scale=(cover?Math.max:Math.min)(c.width/im.width,c.height/im.height);const w=im.width*scale,h=im.height*scale;x.drawImage(im,(c.width-w)/2,(c.height-h)/2,w,h)}
function showCanvas(c){$('#result').replaceChildren();const im=new Image();im.className='preview-image';im.alt='Generated image preview';im.src=c.toDataURL('image/jpeg',.9);$('#result').append(im)}
function addDownload(b,name,text){const a=document.createElement('a');a.textContent=text;a.className='btn p';const url=URL.createObjectURL(b);a.href=url;a.download=name;$('#result').append(a);setTimeout(()=>URL.revokeObjectURL(url),180000)}
function textLine(s){return String(s).replace(/₹/g,'Rs. ').replace(/[\u2013\u2014]/g,'-').replace(/[^\x20-\x7E\n]/g,'?')}
async function linesPDF(lines,name,qr=null){const L=await pdfLib(),doc=await L.PDFDocument.create(),font=await doc.embedFont(L.StandardFonts.Helvetica),bold=await doc.embedFont(L.StandardFonts.HelveticaBold);let p,y;function next(){p=doc.addPage([595,842]);y=790}next();for(const line of lines){const text=textLine(line.text??line),size=line.size||11;const paragraphs=text.split('\n');for(const para of paragraphs){let curr='';for(const word of para.split(' ')){if(font.widthOfTextAtSize(curr+' '+word,size)>480&&curr){if(y<60)next();p.drawText(curr,{x:50,y,size,font:typeof line==='object'&&line.bold?bold:font,color:L.rgb(.1,.1,.1)});y-=size+7;curr=word}else curr+=(curr?' ':'')+word}if(y<60)next();p.drawText(curr,{x:50,y,size,font:typeof line==='object'&&line.bold?bold:font});y-=size+9}}if(qr){if(y<200)next();const im=await doc.embedPng(qr.toDataURL('image/png'));p.drawImage(im,{x:50,y:y-150,width:150,height:150})}save(new Blob([await doc.save()],{type:'application/pdf'}),name)}
// PHOTO: binary search keeps the selected dimensions and finds the best JPEG quality under cap.
if(tool==='photo'){
 const presets={ssc:[300,400],upsc:[350,450],neet:[413,531],jee:[300,400],signature:[400,150],passport:[413,531]};
 $('#preset').onchange=()=>{const p=presets[val('preset')];if(p){$('#width').value=p[0];$('#height').value=p[1]}};
 bind('run',async()=>{const im=await imageFile($('#image').files[0]),w=valid(num('width'),20,4000,'Width'),h=valid(num('height'),20,4000,'Height');if(!Number.isInteger(w)||!Number.isInteger(h))throw Error('Pixel dimensions must be whole numbers.');const c=canvas(w,h);drawFit(im,c);const cap=num('kb')*1024;let lo=.01,hi=1,best=await blob(c,lo);if(best.size>cap)throw Error('This size cannot fit the target even at minimum quality. Reduce pixel dimensions and try again.');for(let i=0;i<15;i++){const mid=(lo+hi)/2,b=await blob(c,mid);if(b.size<=cap){best=b;lo=mid}else hi=mid}showCanvas(c);const detail=document.createElement('p');detail.textContent=`${w} × ${h} pixels · ${(best.size/1024).toFixed(2)} KB · JPEG`;$('#result').prepend(detail);const preview=$('#result img');preview.src=URL.createObjectURL(best);preview.onload=()=>URL.revokeObjectURL(preview.src);addDownload(best,`photo-${num('kb')}kb.jpg`,'Download JPEG');status('Check sharpness and your application rules before uploading.')});
}
function indianWords(n){const ones=['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen'],tens=['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];function w(x){if(x<20)return ones[x];if(x<100)return tens[Math.floor(x/10)]+(x%10?' '+w(x%10):'');if(x<1000)return w(Math.floor(x/100))+' Hundred'+(x%100?' '+w(x%100):'');for(const [v,l] of [[10000000,'Crore'],[100000,'Lakh'],[1000,'Thousand']])if(x>=v)return w(Math.floor(x/v))+' '+l+(x%v?' '+w(x%v):'')}const paise=Math.round(n*100),ru=Math.floor(paise/100),p=paise%100;return (ru?w(ru):'Zero')+' Rupees'+(p?' and '+w(p)+' Paise':'')+' Only'}
if(tool==='invoice'){
 let last=null;const keys=['business','gstin','address','upi'];$('#date').value=new Date().toLocaleDateString('en-CA');try{const p=JSON.parse(localStorage.getItem('sg-business')||'{}');keys.forEach(k=>{if(typeof p[k]==='string')$('#'+k).value=p[k]})}catch{}
 function add(){const tr=document.createElement('tr');tr.innerHTML='<td><input aria-label="Item description / HSN" class="description" maxlength="150"></td><td><input aria-label="Quantity" class="qty" type="number" min="0.01" value="1" step="any"></td><td><input aria-label="Rate" class="price" type="number" min="0" value="0" step="0.01"></td><td><input aria-label="GST percent" class="gst" type="number" min="0" max="100" value="18" step="0.1"></td><td><button type="button" aria-label="Remove item">×</button></td>';tr.querySelector('button').onclick=()=>tr.remove();$('#items').append(tr)}add();bind('add',add);
 bind('profile',()=>{const p={};keys.forEach(k=>p[k]=val(k));localStorage.setItem('sg-business',JSON.stringify(p));status('Business profile saved on this device.')});
 function calculate(){if(!val('business')||!val('customer')||!val('invoice')||!val('date')||!val('address')||!val('place'))throw Error('Enter business name, address, bill-to, invoice number, date and place of supply.');for(const k of ['gstin','buyerGST'])if(val(k)&&!/^\d{2}[A-Z]{5}\d{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(val(k).toUpperCase()))throw Error('GSTIN should have 15 characters in the standard format.');const rows=$$('#items tr').map(tr=>{const description=tr.querySelector('.description').value.trim();if(!description)throw Error('Add a description and HSN where applicable to every item.');const q=valid(Number(tr.querySelector('.qty').value),.001,1e6,'Quantity'),r=valid(Number(tr.querySelector('.price').value),0,1e8,'Rate'),g=valid(Number(tr.querySelector('.gst').value),0,100,'GST rate'),base=Math.round(q*r*100)/100,tax=Math.round(base*g)/100;return{description,q,r,g,base,tax}});if(!rows.length)throw Error('Add at least one item.');const base=rows.reduce((a,r)=>a+r.base,0),tax=rows.reduce((a,r)=>a+r.tax,0),total=Math.round((base+tax)*100)/100;if(total>999999999)throw Error('This simple template supports totals below Rs 100 crore.');const info={};['business','gstin','address','customer','buyerGST','place','invoice','date','taxmode','upi'].forEach(k=>info[k]=val(k));return{rows,base,tax,total,info}}
 async function preview(){last=calculate();const {rows,base,tax,total,info:i}=last;result(`<div class="invoice-preview"><h2>${esc(i.business)}</h2><p>${esc(i.address)}<br>GSTIN: ${esc(i.gstin||'Not supplied')}</p><h3>Invoice ${esc(i.invoice)}</h3><p>Date: ${esc(i.date)} · Place of supply: ${esc(i.place)}<br>Bill to: ${esc(i.customer)}<br>Buyer GSTIN: ${esc(i.buyerGST||'Not supplied')}</p><div class="table-scroll"><table><tr><th>Description / HSN</th><th>Qty</th><th>Rate</th><th>Taxable</th><th>GST</th><th>Tax</th></tr>${rows.map(r=>`<tr><td>${esc(r.description)}</td><td>${r.q}</td><td>${money(r.r)}</td><td>${money(r.base)}</td><td>${r.g}%</td><td>${money(r.tax)}</td></tr>`).join('')}</table></div><p>Taxable value: ${money(base)}</p><p>${i.taxmode==='local'?`CGST: ${money(tax/2)} · SGST: ${money(tax/2)}`:`IGST: ${money(tax)}`}</p><h2>Total: ${money(total)}</h2><p>${indianWords(total)}</p>${i.upi?`<p>UPI: ${esc(i.upi)}</p><div id="invoice-qr"></div>`:''}</div>`);if(i.upi){if(!/^[\w.\-]+@[\w.\-]+$/.test(i.upi))throw Error('Enter a valid UPI ID.');const c=await qrCanvas(upiURI(i.upi,i.business,total));$('#invoice-qr').append(c)}}
 bind('run',preview);bind('pdf',async()=>{await preview();const {rows,base,tax,total,info:i}=last;const lines=[{text:i.business,size:22,bold:true},i.address,'GSTIN: '+(i.gstin||'Not supplied'),{text:`Invoice ${i.invoice}`,size:16,bold:true},'Date: '+i.date,'Place of supply: '+i.place,'Bill to: '+i.customer,'Buyer GSTIN: '+(i.buyerGST||'Not supplied'),' ',...rows.flatMap(r=>[{text:r.description,bold:true},`Qty ${r.q} x ${money(r.r)} | Taxable ${money(r.base)} | GST ${r.g}%: ${money(r.tax)}`]),' ',`Taxable value: ${money(base)}`,i.taxmode==='local'?`CGST: ${money(tax/2)} | SGST: ${money(tax/2)}`:`IGST: ${money(tax)}`,{text:`Total: ${money(total)}`,size:18,bold:true},indianWords(total)];if(i.upi)lines.push('Pay using UPI ID: '+i.upi);await linesPDF(lines,`invoice-${i.invoice.replace(/[^\w-]/g,'_')}.pdf`,i.upi?await qrCanvas(upiURI(i.upi,i.business,total)):null)});
}
function loan(P,annual,N,extra=0){const r=annual/1200,payment=r?P*r/(1-Math.pow(1+r,-N)):P/N;let balance=P,interest=0;const rows=[];for(let m=1;balance>.001&&m<=N+1;m++){const int=balance*r,paid=Math.min(balance+int,payment+extra),principal=paid-int;balance=Math.max(0,balance-principal);interest+=int;rows.push({month:m,paid,int,principal,balance})}return{payment,interest,rows,total:P+interest}}
if(tool==='finance')bind('run',()=>{const P=valid(num('principal'),1,1e10,'Amount'),annual=valid(num('rate'),0,100,'Annual rate'),N=valid(num('months'),1,600,'Months');if(!Number.isInteger(N))throw Error('Months must be a whole number.');const mode=val('mode');if(mode==='emi'){const extra=valid(num('prepay'),0,1e10,'Prepayment'),base=loan(P,annual,N),l=loan(P,annual,N,extra);result(metrics([['Monthly EMI',money(l.payment)],['Interest with prepayment',money(l.interest)],['Payoff',l.rows.length+' months'],['Interest saved',money(base.interest-l.interest)],['Total paid',money(l.total)],['Extra each month',money(extra)]])+`<details><summary>Monthly amortisation (${l.rows.length} payments)</summary><div class="table-scroll"><table><tr><th>Month</th><th>Payment</th><th>Interest</th><th>Principal</th><th>Balance</th></tr>${l.rows.map(r=>`<tr><td>${r.month}</td><td>${money(r.paid)}</td><td>${money(r.int)}</td><td>${money(r.principal)}</td><td>${money(r.balance)}</td></tr>`).join('')}</table></div></details>`);return}const r=annual/1200;let invested,total;if(mode==='fd'){invested=P;total=P*Math.pow(1+annual/400,N/3)}else{invested=P*N;total=r?P*(Math.pow(1+r,N)-1)/r:P*N;if(mode==='sip')total*=1+r}result(metrics([['Invested',money(invested)],['Estimated maturity',money(total)],['Estimated growth',money(total-invested)]])+`<p class="note">${mode==='sip'?'SIP assumes deposits at the start of each month.':'RD assumes month-end deposits; FD assumes quarterly compounding, including fractional quarters.'} Rates remain constant in this estimate.</p>`)});
// QR uses a locally bundled encoder. No external image service receives payment or contact data.
let qrPromise;async function qrCanvas(text){if(!qrPromise)qrPromise=new Promise((r,j)=>{const s=document.createElement('script');s.src='qr-local.js';s.onload=r;s.onerror=()=>{qrPromise=null;j(Error('QR library could not load.'))};document.head.append(s)});await qrPromise;const c=document.createElement('canvas');await window.QRCode.toCanvas(c,text,{width:240,margin:2,errorCorrectionLevel:'M'});c.style.maxWidth='100%';c.setAttribute('aria-label','Generated QR code');return c}
function upiURI(id,name,amount){const q=new URLSearchParams({pa:id,pn:name,cu:'INR'});if(amount>0)q.set('am',Number(amount).toFixed(2));return 'upi://pay?'+q.toString()}
window.SGTools={loan,indianWords,linesPDF};
})();
